version: "3"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    volumes:
      - ./initialization:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s # How often the status will be checked
      retries: 5 # How many times to check before considering it unavailable
      timeout: 10s # Timeout for each test run
    environment:
      MYSQL_DATABASE: bugtracker
      MYSQL_ROOT_PASSWORD: Cookies345
    ports:
      - "3308:3306"
    networks:
      - bugtracker-network

  mysqldemodb:
    image: mysql:8.0
    container_name: mysqldemodb
    restart: always
    volumes:
      - mysqldemodata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 10s
    environment:
      MYSQL_DATABASE: bugtrackerdemo
      MYSQL_ROOT_PASSWORD: Cookies345
    ports:
      - "3307:3306"
    networks:
      - bugtracker-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
      mysqldemodb:
        condition: service_healthy
    restart: on-failure
    networks:
      - bugtracker-network
    environment:
      - SPRING_DB1_DATASOURCE_JDBC_URL=${SPRING_DB1_DATASOURCE_JDBC_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SPRING_DB1_DATASOURCE_USERNAME=${SPRING_DB1_DATASOURCE_USERNAME}
      - SPRING_DB1_DATASOURCE_PASSWORD=${SPRING_DB1_DATASOURCE_PASSWORD}
      - SPRING_DB1_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DB1_DATASOURCE_DRIVER_CLASS_NAME}

      - SPRING_DB2_DATASOURCE_JDBC_URL=${SPRING_DB2_DATASOURCE_JDBC_URL}
      - MYSQL_DATABASE2=${MYSQL_DATABASE2}
      - SPRING_DB2_DATASOURCE_USERNAME=${SPRING_DB2_DATASOURCE_USERNAME}
      - SPRING_DB2_DATASOURCE_PASSWORD=${SPRING_DB2_DATASOURCE_PASSWORD}
      - SPRING_DB2_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DB2_DATASOURCE_DRIVER_CLASS_NAME}

      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=${SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS}

  frontend:
    container_name: frontend
    build:
      context: ..\Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - bugtracker-network


networks:
  bugtracker-network:
    driver: bridge

volumes:
  mysqldata:
  mysqldemodata:


